export {
  BUTTER_DEBRIS_BODY_LIMIT,
  BUTTER_DEFINITIONS,
  BUTTER_SOURCE_SEGMENTS,
  BUTTER_SYNESTHESIA_PALETTE,
  BUTTER_STACK_GROUND_Y,
  BUTTER_STACK_HEIGHT,
  BUTTER_STACK_PLATE_COUNT,
  BUTTER_STACK_POSITIONS,
  BUTTER_STACK_SHELL_HEIGHT,
  BUTTER_STACK_STEP,
  mixButterSeed,
} from './butterCatalog'
export type {
  ButterDefinition,
  ButterId,
  ButterVector3,
  ButterWaxPalette,
} from './butterCatalog'
